# Generated by Django 3.2.16 on 2024-12-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20241221_1824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
